[env]
WINIT_X11_SCALE_FACTOR = "1.0"

[scrolling]
history = 10000
multiplier = 3

[window]
padding = { x = 3, y = 3 }
dynamic_padding = true
decorations_theme_variant = "None"
decorations = "none"
opacity = 0.9
blur = false
startup_mode = "Windowed"
title = "Alacritty"
dynamic_title = true
resize_increments = true

[font]
normal = { family = "JetBrainsMonoNL Nerd Font", style = "Medium" }
size = 12
builtin_box_drawing = true

[bell]
animation = "Linear"
duration = 0

[selection]
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"
save_to_clipboard = true

[cursor]
style = { shape = "Block", blinking = "Off" }
unfocused_hollow = true
thickness = 0.15

[mouse]
hide_when_typing = false

[general]
live_config_reload = true
import = [
  "~/.config/alacritty/colors.toml",
  "~/.config/alacritty/keybindings.toml",
]

# [terminal.shell]
# program = "/bin/zsh"
# args = ["-l"]

[[hints.enabled]]
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini://|gopher://|https://|http://|news:|file:|git://|ssh:|ftp://)[^\\u0000-\\u001F\\u007F-\\u009F<>\"\\s{-}\\^⟨⟩`]+"
hyperlinks = true
post_processing = true
persist = false
mouse.enabled = true
binding = { key = "U", mods = "Control|Shift" }
command = "xdg-open"

[terminal]

