[keyboard]
bindings = [
  { key = "N", mods = "Control|Shift", action = "CreateNewWindow" },
  { key = "C", mods = "Control|Shift", action = "Copy" },
  { key = "V", mods = "Control|Shift", action = "Paste" },
  { key = "Equals", mods = "Control", action = "IncreaseFontSize" },
  { key = "Minus", mods = "Control", action = "DecreaseFontSize" },
  { key = "Key0", mods = "Control", action = "ResetFontSize" },
  { key = "PageUp", action = "ScrollPageUp" },
  { key = "PageDown", action = "ScrollPageDown" },
  { key = "Up", mods = "Control", action = "ScrollLineUp" },
  { key = "Down", mods = "Control", action = "ScrollLineDown" },
  { key = "F11", action = "ToggleFullscreen" },
  { key = "L", mods = "Control|Shift", chars = "ls -la\n" },
]
