from typing import Any, Dict, List, Optional, Tuple

class VolumeSettings(Dict[str, Any]): ...

VOLUME_CONFIG: Dict[str, VolumeSettings]

VOLUME_STEP: int
CACHE_TIMEOUT: float
DEBOUNCE_TIMEOUT: float
CMD_TIMEOUT: float

def run_cmd(cmd: List[str]) -> str: ...
def parse_wpctl_output(output: str) -> Tuple[int, bool]: ...

class AudioWidget:
    def __init__(
        self,
        kind: str = ...,
        device: Optional[str] = ...,
        update_interval: float = ...,
        **config: Any,
    ) -> None: ...
    def _get_volume_info(self, force_refresh: bool = ...) -> Tuple[int, bool]: ...
    def _format_display(self, volume: int, muted: bool) -> str: ...
    def _poll(self) -> str: ...
    def _execute_volume_cmd(self, cmd: List[str]) -> None: ...
    def volume_up(self) -> None: ...
    def volume_down(self) -> None: ...
    def toggle_mute(self) -> None: ...
    def get_state(self) -> Dict[str, Any]: ...

class MicWidget(AudioWidget):
    def __init__(self, **config: Any) -> None: ...
