# Schema definition
"$schema" = "https://yazi-rs.github.io/schemas/keymap.json"

# Manager keymaps
[mgr]
keymap = [
  # ─────────────── General ───────────────
  { on = [
    "<Esc>",
    "<C-[>",
  ], run = "escape", desc = "Exit visual mode, clear selected, or cancel search" },
  { on = [
    "q",
  ], run = "quit", desc = "Exit the process" },
  { on = [
    "Q",
  ], run = "quit --no-cwd-file", desc = "Exit without writing cwd-file" },
  { on = [
    "<C-c>",
  ], run = "close", desc = "Close tab or quit" },
  { on = [
    "<C-z>",
  ], run = "suspend", desc = "Suspend the process" },

  # ─────────────── Movement ───────────────
  { on = [
    "k",
    "<Up>",
  ], run = "arrow -1", desc = "Move up" },
  { on = [
    "j",
    "<Down>",
  ], run = "arrow 1", desc = "Move down" },
  { on = [
    "<C-u>",
    "<S-PageUp>",
  ], run = "arrow -50%", desc = "Move up half page" },
  { on = [
    "<C-d>",
    "<S-PageDown>",
  ], run = "arrow 50%", desc = "Move down half page" },
  { on = [
    "<C-b>",
    "<PageUp>",
  ], run = "arrow -100%", desc = "Move up one page" },
  { on = [
    "<C-f>",
    "<PageDown>",
  ], run = "arrow 100%", desc = "Move down one page" },
  { on = [
    "g",
    "g",
  ], run = "arrow -99999999", desc = "Move to top" },
  { on = [
    "G",
  ], run = "arrow 99999999", desc = "Move to bottom" },

  # ─────────────── Navigation ───────────────
  { on = [
    "h",
    "<Left>",
  ], run = "leave", desc = "Go to parent directory" },
  { on = [
    "l",
    "<Right>",
  ], run = "enter", desc = "Enter directory" },
  { on = [
    "H",
  ], run = "back", desc = "Back to previous directory" },
  { on = [
    "L",
  ], run = "forward", desc = "Forward to next directory" },
  { on = [
    "c",
    "d",
  ], run = "shell 'cd' --interactive", desc = "Change directory manually" },

  # ─────────────── Selection ───────────────
  { on = [
    "v",
  ], run = "visual_mode", desc = "Enter visual mode" },
  { on = [
    "V",
  ], run = "visual_mode --linewise", desc = "Enter visual mode (linewise)" },
  { on = [
    " ",
  ], run = "select", desc = "Toggle selection" },
  { on = [
    "Y",
  ], run = "select_all", desc = "Select all" },

  # ─────────────── File Operations ───────────────
  { on = [
    "o",
  ], run = "open", desc = "Open file(s)" },
  { on = [
    "O",
  ], run = "open --interactive", desc = "Open interactively" },
  { on = [
    "d",
    "d",
  ], run = "remove", desc = "Move to trash" },
  { on = [
    "D",
  ], run = "remove --permanently", desc = "Delete permanently" },
  { on = [
    "y",
    "y",
  ], run = "copy", desc = "Copy" },
  { on = [
    "y",
    "x",
  ], run = "copy --cut", desc = "Cut" },
  { on = [
    "p",
    "p",
  ], run = "paste", desc = "Paste" },
  { on = [
    "P",
    "P",
  ], run = "paste --overwrite", desc = "Paste and overwrite" },
  { on = [
    "c",
    "w",
  ], run = "rename", desc = "Rename" },
  { on = [
    "C",
  ], run = "create", desc = "Create file/dir" },
  { on = [
    "a",
  ], run = "archive", desc = "Archive" },
  { on = [
    "x",
  ], run = "extract", desc = "Extract archive" },

  # ─────────────── Searching ───────────────
  { on = [
    "/",
  ], run = "search", desc = "Search files" },
  { on = [
    "?",
  ], run = "search --reverse", desc = "Reverse search" },
  { on = [
    "n",
  ], run = "search_next", desc = "Next result" },
  { on = [
    "N",
  ], run = "search_prev", desc = "Previous result" },

  # ─────────────── Sorting ───────────────
  { on = [
    "s",
    "a",
  ], run = "sort 'alphabetical'", desc = "Sort by name" },
  { on = [
    "s",
    "A",
  ], run = "sort 'alphabetical' --reverse", desc = "Sort by name (reverse)" },
  { on = [
    "s",
    "m",
  ], run = "sort 'modified'", desc = "Sort by modified time" },
  { on = [
    "s",
    "M",
  ], run = "sort 'modified' --reverse", desc = "Sort by modified time (reverse)" },
  { on = [
    "s",
    "c",
  ], run = "sort 'created'", desc = "Sort by created time" },
  { on = [
    "s",
    "C",
  ], run = "sort 'created' --reverse", desc = "Sort by created time (reverse)" },
  { on = [
    "s",
    "s",
  ], run = "sort 'size'", desc = "Sort by size" },
  { on = [
    "s",
    "S",
  ], run = "sort 'size' --reverse", desc = "Sort by size (reverse)" },
  { on = [
    "s",
    "e",
  ], run = "sort 'extension'", desc = "Sort by extension" },
  { on = [
    "s",
    "E",
  ], run = "sort 'extension' --reverse", desc = "Sort by extension (reverse)" },

  # ─────────────── Tabs ───────────────
  { on = [
    "t",
  ], run = "tab_create", desc = "New tab" },
  { on = [
    "T",
  ], run = "tab_create --current", desc = "New tab (current dir)" },
  { on = [
    "<C-w>",
  ], run = "tab_close", desc = "Close tab" },
  { on = [
    "]",
  ], run = "tab_next", desc = "Next tab" },
  { on = [
    "[",
  ], run = "tab_prev", desc = "Previous tab" },
  { on = [
    "}",
  ], run = "tab_swap 1", desc = "Swap with next tab" },
  { on = [
    "{",
  ], run = "tab_swap -1", desc = "Swap with previous tab" },

  # ─────────────── Find/Filter ───────────────
  { on = [
    "f",
  ], run = "find", desc = "Find files by name" },
  { on = [
    "F",
  ], run = "find --interactive", desc = "Find files (interactive)" },
  { on = [
    "S",
  ], run = "filter", desc = "Filter files by name" },

  # ─────────────── Shell ───────────────
  { on = [
    "!",
  ], run = "shell", desc = "Execute command" },
  { on = [
    "@",
  ], run = "shell --block", desc = "Execute in new terminal" },
  { on = [
    "%",
  ], run = "shell --dump", desc = "Execute and dump output" },

  # ─────────────── Toggle Options ───────────────
  { on = [
    "z",
    "h",
  ], run = "toggle_hidden", desc = "Toggle hidden files" },
  { on = [
    "z",
    "i",
    "z",
    "z",
  ], run = "toggle_follow_symlink", desc = "Toggle follow symlinks" },
  { on = [
    "z",
    "s",
  ], run = "toggle_show_symlink_as_file", desc = "Toggle show symlink as file" },
  { on = [
    "z",
    "l",
  ], run = "linemode", desc = "Cycle linemode" },
  { on = [
    "z",
    "L",
  ], run = "linemode --reverse", desc = "Cycle linemode (reverse)" },
  { on = [
    "z",
    "p",
  ], run = "toggle_preview", desc = "Toggle preview" },
  { on = [
    "z",
    "P",
  ], run = "toggle_preview --scope=parent", desc = "Toggle parent preview" },
  { on = [
    "z",
    "t",
  ], run = "toggle_task_show_on_top", desc = "Toggle task display" },
  { on = [
    "z",
    "v",
  ], run = "toggle_visual_selection", desc = "Toggle visual selection" },

  # ─────────────── select ───────────────
  { on = [

    "<Esc>",

  ], run = "close", desc = "Close the select dialog" },

  { on = [

    "q",

  ], run = "close", desc = "Close the select dialog" },

  { on = [

    "j",

  ], run = "arrow 1", desc = "Move cursor down" },

  { on = [

    "k",

  ], run = "arrow -1", desc = "Move cursor up" },

  { on = [

    "<Down>",

  ], run = "arrow 1", desc = "Move cursor down" },

  { on = [

    "<Up>",

  ], run = "arrow -1", desc = "Move cursor up" },

  { on = [

    "<Enter>",

  ], run = "select", desc = "Select the item" },

  # ─────────────── Select ───────────────
  { on = [
    "<Esc>",
    "q",
  ], run = "close", desc = "Close the select dialog" },
  { on = [
    "j",
    "<Down>",
  ], run = "arrow 1", desc = "Move cursor down" },
  { on = [
    "k",
    "<Up>",
  ], run = "arrow -1", desc = "Move cursor up" },
  { on = [
    "<Enter>",
  ], run = "select", desc = "Select the item" },


  # ─────────────── Completion ───────────────
  { on = [
    "<Esc>",
    "<C-c>",
  ], run = "close", desc = "Close the completion menu" },
  { on = [
    "<Tab>",
  ], run = "arrow 1", desc = "Move to the next item" },
  { on = [
    "<S-Tab>",
  ], run = "arrow -1", desc = "Move to the previous item" },
  { on = [
    "<Enter>",
  ], run = "select", desc = "Select the item" },

  # ─────────────── Misc ───────────────
  { on = [
    "~",
    "<F1>",
  ], run = "help", desc = "Show help" },
  { on = [
    "<C-r>",
  ], run = "refresh", desc = "Refresh directory" },
]
