local languages = {
	"bash",
	"c",
	"cpp",
	"lua",
	"python",
	"javascript",
	"typescript",
	"html",
	"css",
	"json",
	"markdown",
	"markdown_inline",
	"vim",
	"vimdoc",
	"rust",
	"regex",
	"latex",
	"yaml",
	"scss",
	"svelte",
	"tsx",
	"typst",
	"vue",
}
return {
	{
		"nvim-treesitter/nvim-treesitter",
		branch = "main",
		build = ":TSUpdate",
	},
	{
		"MeanderingProgrammer/treesitter-modules.nvim",
		dependencies = { "nvim-treesitter/nvim-treesitter" },
		opts = {
			ensure_installed = languages,
			fold = { enable = true },
			highlight = { enable = true },
			indent = { enable = true },
			incremental_selection = { enable = true },
		},
	},
}
